
export const getCalendarSourceMap = (
  personalCalendars,
  sharedUserCalendars,
  tokenCalendars
) => ({
  personal: {
    fetchSchedule: personalCalendars.fetchPersonalCalendarSchedule,
    calendarsData: personalCalendars.calendarsData,
    setCalendarsData: personalCalendars.setCalendarsData,
    updateBox: personalCalendars.updatePersonalBox,
    createBox: personalCalendars.createPersonalBox,
    deleteBox: personalCalendars.deletePersonalBox,
    downloadCalendarPdf: personalCalendars.downloadPersonalCalendarPdf,
    deleteCalendar: personalCalendars.deleteCalendar,
    fetchIfPillboxUsed: personalCalendars.fetchIfPersonalPillboxUsed,
    decreaseStock: personalCalendars.useMedicinesForPersonalPillbox,
    cancelUse: personalCalendars.cancelUsePersonalPillbox,
    fetchPillboxUses: personalCalendars.fetchPersonalPillboxUses,
    restockBox: personalCalendars.personalRestockBox,
    fetchNotificationsEnabled: personalCalendars.fetchPersonalNotificationsEnabled,
    updateNotificationsEnabled: personalCalendars.updatePersonalNotificationsEnabled,
    fetchStockDecrementMethod: personalCalendars.fetchPersonalStockDecrementMethod,
    getTokensIcs: personalCalendars.getTokensIcs,
    createTokenIcs: personalCalendars.createTokenIcs,
    deleteTokenIcs: personalCalendars.deleteTokenIcs,
    },
  sharedUser: {
    fetchSchedule: sharedUserCalendars.fetchSharedUserCalendarSchedule,
    calendarsData: sharedUserCalendars.sharedCalendarsData,
    setCalendarsData: sharedUserCalendars.setSharedCalendarsData,
    updateBox: sharedUserCalendars.updateSharedUserBox,
    createBox: sharedUserCalendars.createSharedUserBox,
    deleteBox: sharedUserCalendars.deleteSharedUserBox,
    downloadCalendarPdf: personalCalendars.downloadPersonalCalendarPdf,
    deleteCalendar: null,
    fetchIfPillboxUsed: sharedUserCalendars.fetchIfSharedUserPillboxUsed,
    decreaseStock: sharedUserCalendars.useMedicinesForSharedUserPillbox,
    cancelUse: sharedUserCalendars.cancelUseSharedUserPillbox,
    fetchPillboxUses: sharedUserCalendars.fetchSharedUserPillboxUses,
    restockBox: sharedUserCalendars.sharedUserRestockBox,
    fetchNotificationsEnabled: sharedUserCalendars.fetchSharedUserNotificationsEnabled,
    updateNotificationsEnabled: sharedUserCalendars.updateSharedUserNotificationsEnabled,
    fetchStockDecrementMethod: sharedUserCalendars.fetchSharedUserStockDecrementMethod,
    getTokensIcs: sharedUserCalendars.getSharedTokensIcs,
    createTokenIcs: sharedUserCalendars.createSharedTokenIcs,
    deleteTokenIcs: sharedUserCalendars.deleteSharedTokenIcs,
  },
  token: {
    fetchSchedule: tokenCalendars.fetchTokenCalendarSchedule,
    calendarsData: null,
    setCalendarsData: null,
    // TODO: add updateBox for tokenCalendars
    updateBox: null,
    createBox: null,
    deleteBox: null,
    downloadCalendarPdf: null,
    deleteCalendar: null,
    fetchIfPillboxUsed: null,
    decreaseStock: null,
    cancelUse: null,
    fetchPillboxUses: null,
    restockBox: null,
    fetchNotificationsEnabled: null,
    updateNotificationsEnabled: null,
    fetchStockDecrementMethod: null,
    getTokensIcs: null,
    createTokenIcs: null,
    deleteTokenIcs: null,
  },
});
